Add a debug flag
Currently, it only tweaks the validated result exception but
it could be used for other things. Current implementation rebuild
the exception with only DANGER and ERROR validation event when debug
is false. Which is the default.

It looks like this:

```
An error occurred while importing your Open API resources.
software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events:
[ERROR] issue_23#TestersGetTest: Operation URI, `/Testers/{id}`, conflicts with other operation URIs in the same service: [`issue_23#TestersGetTestTags` (/Testers/queries/unique-tags)] | HttpUriConflict N/A:0:0
[ERROR] issue_23#TestersGetTestTags: Operation URI, `/Testers/queries/unique-tags`, conflicts with other operation URIs in the same service: [`issue_23#TestersGetTest` (/Testers/{id})] | HttpUriConflict N/A:0:0
	at smithytranslate.openapi.OpenApiCompiler$Options.$anonfun$debugModelValidationError$1(OpenApiCompiler.scala:97)
	at cats.syntax.EitherOps$.leftMap$extension(either.scala:193)
	at smithytranslate.openapi.OpenApiCompiler$.compile(OpenApiCompiler.scala:159)
	at smithytranslate.openapi.OpenApiCompiler$.parseAndCompile(OpenApiCompiler.scala:142)
	at smithytranslate.cli.runners.openapi.ParseAndCompile$.openapi(ParseAndCompile.scala:42)
	at smithytranslate.cli.runners.OpenApi$.runOpenApi(OpenApi.scala:36)
	at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:34)
	at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:32)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at cats.data.Validated.andThen(Validated.scala:727)
	at com.monovore.decline.Result.$anonfun$mapValidated$2(Result.scala:13)
	at cats.instances.Function0Instances$$anon$4.$anonfun$map$1(function.scala:96)
	at com.monovore.decline.Parser.evalResult(Parser.scala:30)
	at com.monovore.decline.Parser.$anonfun$consumeAll$3(Parser.scala:107)
	at scala.util.Either.flatMap(Either.scala:352)
	at com.monovore.decline.Parser.$anonfun$consumeAll$1(Parser.scala:107)
	at scala.Option.map(Option.scala:242)
	at com.monovore.decline.Parser.consumeAll(Parser.scala:106)
	at com.monovore.decline.Parser.apply(Parser.scala:19)
	at com.monovore.decline.Command.parse(opts.scala:20)
	at smithytranslate.cli.CommandApp.main(CommandApp.scala:81)
	at smithytranslate.cli.Main.main(Main.scala)

```

When debug is set to true, you see all validation events:

```
An error occurred while importing your Open API resources.
software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events:
[ERROR] issue_23#TestersGetTest: Operation URI, `/Testers/{id}`, conflicts with other operation URIs in the same service: [`issue_23#TestersGetTestTags` (/Testers/queries/unique-tags)] | HttpUriConflict N/A:0:0
[ERROR] issue_23#TestersGetTestTags: Operation URI, `/Testers/queries/unique-tags`, conflicts with other operation URIs in the same service: [`issue_23#TestersGetTest` (/Testers/{id})] | HttpUriConflict N/A:0:0
[SUPPRESSED] smithytranslate#Null: The structure shape is not connected to from any service shape. (This is a library namespace.) | UnreferencedShape /Users/David.Francoeur/workspace/dev/smithy-translate/modules/traits/resources/META-INF/smithy/openapi.smithy:37:1
[WARNING] issue_23#TestersGetTest: This operation uses the `GET` method in the `http` trait, but is not marked with the readonly trait | HttpMethodSemantics N/A:0:0
[WARNING] issue_23#TestersGetTestTags: This operation uses the `GET` method in the `http` trait, but is not marked with the readonly trait | HttpMethodSemantics N/A:0:0
	at software.amazon.smithy.model.validation.ValidatedResult.validate(ValidatedResult.java:145)
	at software.amazon.smithy.model.validation.ValidatedResult.unwrap(ValidatedResult.java:132)
	at smithytranslate.openapi.OpenApiCompiler$.validate(OpenApiCompiler.scala:168)
	at smithytranslate.openapi.OpenApiCompiler$.$anonfun$compile$5(OpenApiCompiler.scala:157)
	at scala.util.Try$.apply(Try.scala:210)
	at smithytranslate.openapi.OpenApiCompiler$.compile(OpenApiCompiler.scala:157)
	at smithytranslate.openapi.OpenApiCompiler$.parseAndCompile(OpenApiCompiler.scala:142)
	at smithytranslate.cli.runners.openapi.ParseAndCompile$.openapi(ParseAndCompile.scala:42)
	at smithytranslate.cli.runners.OpenApi$.runOpenApi(OpenApi.scala:36)
	at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:34)
	at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:32)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at cats.data.Validated.andThen(Validated.scala:727)
	at com.monovore.decline.Result.$anonfun$mapValidated$2(Result.scala:13)
	at cats.instances.Function0Instances$$anon$4.$anonfun$map$1(function.scala:96)
	at com.monovore.decline.Parser.evalResult(Parser.scala:30)
	at com.monovore.decline.Parser.$anonfun$consumeAll$3(Parser.scala:107)
	at scala.util.Either.flatMap(Either.scala:352)
	at com.monovore.decline.Parser.$anonfun$consumeAll$1(Parser.scala:107)
	at scala.Option.map(Option.scala:242)
	at com.monovore.decline.Parser.consumeAll(Parser.scala:106)
	at com.monovore.decline.Parser.apply(Parser.scala:19)
	at com.monovore.decline.Command.parse(opts.scala:20)
	at smithytranslate.cli.CommandApp.main(CommandApp.scala:81)
	at smithytranslate.cli.Main.main(Main.scala)

```